/** Section content for routed pages. */
function cards(a, b, c, d, e, f) {
  return [
    { title: a, text: b },
    { title: c, text: d },
    { title: e, text: f },
  ]
}

export const sectionCopy = {
  accounts: {
    title: 'Accounts',
    lead:
      'Savings, current, and salary accounts with digital onboarding and 24/7 service.',
    cards: cards(
      'Savings account',
      'Interest-bearing accounts with passbook and passbookless options, joint holding, and nomination.',
      'Current account',
      'High transaction limits, overdraft where eligible, and integrated collections for business.',
      'Salary account',
      'Zero-balance options with employer tie-ups, auto sweep, and preferential service.',
    ),
    bullets: [
      'Insta account opening and video KYC where available',
      'SMS and email alerts on credits and debits',
    ],
  },
  cards: {
    title: 'Cards',
    lead: 'Credit, debit, forex, and commercial cards for individuals and businesses.',
    cards: cards(
      'Credit cards',
      'Rewards, travel, fuel, and dining programmes with add-on cards for family members.',
      'Debit cards',
      'Secure PIN, contactless limit controls, and instant hotlisting from the app.',
      'Forex & commercial',
      'Multi-currency travel cards and business expense cards with consolidated statements.',
    ),
    bullets: ['Apple Pay, Google Pay, and Samsung Pay support where enabled'],
  },
  loans: {
    title: 'Loans',
    lead: 'Home, personal, car, and gold loans with competitive rates and quick processing.',
    cards: cards(
      'Home loan',
      'Balance transfer, top-up, and pre-approved offers for select customers.',
      'Personal & auto',
      'Fixed tenure EMIs, part-prepayment, and online sanction tracking.',
      'Gold loan',
      'Quick release against gold with minimal documentation at branches.',
    ),
    bullets: ['Eligibility and EMI calculator available online'],
  },
  investments: {
    title: 'Investments',
    lead: 'Mutual funds, demat, and wealth solutions to help you plan your goals.',
    cards: cards(
      'Mutual funds',
      'Direct and regular plans, SIP, STP, SWP, and risk-labelled categories.',
      'Equities & demat',
      'Trading and custody with net banking integration for pay-ins and payouts.',
      'Wealth services',
      'Goal tracking, model portfolios, and review cadence with relationship managers.',
    ),
    bullets: ['Statements and capital gains views on digital channels'],
  },
  insurance: {
    title: 'Insurance',
    lead: 'Life, health, motor, and travel coverage through trusted partners.',
    cards: cards(
      'Health',
      'Individual and family floaters, cashless network hospitals, and wellness benefits.',
      'Motor',
      'Comprehensive and third-party plans with add-ons and NCB transfer.',
      'Travel & home',
      'Trip cancellation, baggage cover, and home contents on selected plans.',
    ),
    bullets: ['Renewals and endorsements on self-service where supported'],
  },
  forex: {
    title: 'Forex',
    lead: 'Buy and sell foreign currency, travel cards, and outward remittances.',
    cards: cards(
      'Currency',
      'Banknotes and pre-paid travel cards in major world currencies.',
      'Remittances',
      'Outward wire, demand drafts, and student remittance on eligible purposes.',
      'Rates & limits',
      'Live board rates, same-day delivery at select locations, and limit checks.',
    ),
    bullets: ['FCNR(B) and NRE deposit options for eligible customers'],
  },
  pay: {
    title: 'Pay',
    lead: 'UPI, bill pay, and merchant solutions for fast, secure payments.',
    cards: cards(
      'UPI & IMPS',
      'Person-to-person and merchant UPI; IMPS 24/7 to registered beneficiaries.',
      'Bills & recharge',
      'Utilities, fast tag, DTH, and subscription payments in one place.',
      'Business',
      'Soundbox, static and dynamic QR, and settlement reports for merchants.',
    ),
    bullets: ['NEFT and RTGS with beneficiary cooling period where required'],
  },
  smartbuy: {
    title: 'SmartBuy',
    lead: 'Deals and offers on shopping, travel, and lifestyle partners.',
    cards: cards(
      'Shopping',
      'Electronics, appliances, and gift cards on EMI with card offers.',
      'Travel',
      'Flights, hotels, and holidays with card-specific cashbacks.',
      'Lifestyle',
      'Dining, entertainment, and wellness discounts on select days.',
    ),
    bullets: ['Offers updated frequently; see detail pages for T&Cs'],
  },
  'private-banking': {
    title: 'Private Banking',
    lead: 'Dedicated relationship management and tailored wealth solutions.',
    cards: cards(
      'Relationship',
      'Named coverage across banking, investments, and credit.',
      'Wealth & trust',
      'Bespoke asset allocation, credit lines, and executor services on request.',
      'Lifestyle',
      'Invitations to client events, airport services, and concierge tie-ups on eligible programmes.',
    ),
    bullets: ['Minimum relationship criteria apply; offered by invite or upgrade'],
  },
  offers: {
    title: 'Offers',
    lead: 'Limited-time offers on cards, accounts, and loans. Check back often.',
    cards: cards(
      'Cards',
      'Welcome bonuses, fee waivers, and bonus reward points for new issuances.',
      'Loans & mortgage',
      'Rate specials, zero processing, and cashbacks on selected schemes.',
      'Accounts',
      'Cashback on salary credits and refer-a-friend on selected programmes.',
    ),
    bullets: ['Each offer has eligibility rules and an end date'],
  },
  personal: {
    title: 'Personal banking',
    lead: 'Everyday banking for individuals and families.',
    cards: cards(
      'Save & transact',
      'Savings, salary, and senior citizen accounts with doorstep and digital channels.',
      'Borrow & protect',
      'Personal loans, two-wheeler loans, and general insurance on compatible journeys.',
      'Invest & pay',
      'SIP, UPI, and bill pay from one login with unified statements.',
    ),
    bullets: ['NetBanking, MobileBanking, and phone banking for service requests'],
  },
  wholesale: {
    title: 'Wholesale banking',
    lead: 'Working capital, trade, and cash management for enterprises.',
    cards: cards(
      'Working capital',
      'Cash credit, overdraft, and receivable financing with covenant monitoring.',
      'Trade',
      'LCs, bank guarantees, and supply chain finance on approved limits.',
      'Cash management',
      'Collections, virtual accounts, and multi-location pooling.',
    ),
    bullets: ['Relationship coverage for mid-market and large corporates'],
  },
  nri: {
    title: 'NRI banking',
    lead: 'Accounts and remittances for non-resident Indians.',
    cards: cards(
      'NRE & NRO',
      'Repatriable and non-repatriable operating accounts in INR.',
      'FCNR(B)',
      'Foreign currency fixed deposits in USD, GBP, EUR, and more.',
      'Remittances',
      'Inward and outward remittance with FEMA-compliant documentation support.',
    ),
    bullets: ['Tax residence and DTA guidance through qualified advisors'],
  },
  agri: {
    title: 'Agri banking',
    lead: 'Credit and support for farmers and agri businesses.',
    cards: cards(
      'Kisan & crop',
      'Short-term production credit linked to land records where integrated.',
      'Agri business',
      'Agri term loans, warehouse receipt finance, and cold chain support.',
      'Advisory',
      'Crop calendar reminders and market awareness sessions at select centres.',
    ),
    bullets: ['Government interest subvention on eligible Kisan products'],
  },
  sme: {
    title: 'SME banking',
    lead: 'Loans, accounts, and digital tools for small and medium enterprises.',
    cards: cards(
      'Business accounts',
      'Current accounts, escrow, and virtual accounts for projects.',
      'Credit',
      'Term loans, working capital, and equipment finance on cash-flow assessment.',
      'Digital',
      'POS, QR, and payables batch upload with reconciliation views.',
    ),
    bullets: ['Relationship managers in major SME clusters'],
  },
  startup: {
    title: 'Start-up banking',
    lead: 'Current accounts, founder credit, and partner ecosystem for new ventures.',
    cards: cards(
      'Start account',
      'Simplified KYC, multi-signatory, and low balance maintenance options.',
      'Founder credit',
      'Unsecured and secured lines subject to business plan and bureau checks.',
      'Partners',
      'Introductions to accelerators, cloud providers, and legal firms on the panel.',
    ),
    bullets: ['Programme eligibility and limits vary by location'],
  },
  csr: {
    title: 'CSR',
    lead: 'Community and sustainability initiatives across education, health, and environment.',
    cards: cards(
      'Education',
      'Scholarships, school infrastructure, and financial literacy.',
      'Health',
      'Rural health camps, equipment donation, and awareness drives.',
      'Sustainability',
      'Tree plantation, water conservation, and energy efficiency in operations.',
    ),
    bullets: ['Annual reporting on CSR outlays as per regulations'],
  },
  'ways-to-bank': {
    title: 'Ways to bank',
    lead: 'Bank online, on mobile, at ATMs, branches, or from your premises.',
    cards: cards(
      'Digital',
      'NetBanking, MobileBanking, and WhatsApp for select queries and alerts.',
      'Branch & ATM',
      'Passbook update, cash and cheque, and passbook kiosks where installed.',
      'Phone & chat',
      'IVR, agent telephony, and secure messaging on authenticated sessions.',
    ),
    bullets: ['Biometric and device binding for high-risk actions'],
  },
  discover: {
    title: 'Discover',
    lead: 'Explore products, read security advice, and stay updated on new launches.',
    cards: cards(
      'Products',
      'Feature guides, comparison tables, and FAQs by category.',
      'Security',
      'Phishing awareness, strong passwords, and transaction verification.',
      'Stories',
      'Customer and community highlights from the bank’s channels.',
    ),
    bullets: ['Subscribe to email updates on selected topics'],
  },
  group: {
    title: 'HDFC Group',
    lead: 'A diversified group spanning banking, insurance, asset management, and housing finance.',
    cards: cards(
      'Banking',
      'Retail, wholesale, and treasury for individuals and institutions.',
      'Insurance & HFC',
      'Life, general, and housing finance for protection and long-term needs.',
      'AMC & others',
      'Asset management, education loans, and proprietary investments.',
    ),
    bullets: ['Each group company is separately regulated and capitalised'],
  },
  support: {
    title: 'Customer care',
    lead: 'Reach us any time for cards, accounts, loans, and digital support.',
    cards: cards(
      'Phone',
      'Domestic and international helplines with priority for senior citizens and NRI desk.',
      'Digital',
      'Secure email, in-app chat, and dispute logging with ticket numbers.',
      'Branch',
      'Relationship managers and service requests at your home branch or shared network.',
    ),
    bullets: ['Keep your customer ID and registered mobile ready for authentication'],
  },
  about: {
    title: 'About us',
    lead: 'Our history, values, and leadership in serving customers across the country.',
    cards: cards(
      'Heritage',
      'Decades of retail and wholesale banking with nationwide presence.',
      'Values',
      'Customer focus, integrity, and responsible growth.',
      'Leadership',
      'Board, management, and governance aligned to statutory and regulatory standards.',
    ),
    bullets: ['Annual reports, sustainability disclosures, and media centre'],
  },
  careers: {
    title: 'Careers',
    lead: 'Build a career in banking, technology, risk, and operations with growth opportunities.',
    cards: cards(
      'Hiring',
      'Campus, lateral, and specialist hiring across functions.',
      'Culture',
      'Learning, diversity, and internal mobility on merit.',
      'Application',
      'Online profile, assessment, and status tracking in the careers portal.',
    ),
    bullets: ['Equal opportunity employer; accommodations for persons with disability where feasible'],
  },
  investors: {
    title: 'Investor relations',
    lead: 'Reports, filings, and shareholder information in one place.',
    cards: cards(
      'Results',
      'Quarterly and annual results with management commentary and investor calls.',
      'Shareholder services',
      'Dividend, demat, and IEPF in line with record dates.',
      'Governance',
      'Board composition, committee charters, and policies in the governance section.',
    ),
    bullets: ['Stock exchange filings and press releases in real time'],
  },
  locate: {
    title: 'Locate us',
    lead: 'Find branches, ATMs, and loan centres by city, pincode, and services required.',
    cards: cards(
      'Branch',
      'Account opening, locker, and large-cash services by appointment.',
      'ATM & CRM',
      'Cash out, passbook kiosks, and cheque drop where available.',
      'Select services',
      'Forex, wealth, and NRI special desks in metro locations.',
    ),
    bullets: ['Branch timings may vary on holidays; call ahead for locker visits'],
  },
  language: {
    title: 'Language',
    lead: 'Choose a language for pages and service communications where available.',
    cards: cards(
      'Interface',
      'English, हिंदी, and more on compatible browsers and app versions.',
      'Statements',
      'eStatements and select SMS in chosen language for registered users.',
      'Assistance',
      'Multilingual IVR and branch assistance in major Indian languages in select areas.',
    ),
    bullets: ['Language preference can be updated in profile settings'],
  },
  privacy: {
    title: 'Privacy policy',
    lead: 'How we collect, use, and protect your personal data across channels.',
    cards: cards(
      'Data use',
      'Service delivery, risk, regulatory reporting, and product improvement with lawful basis.',
      'Your choices',
      'Access, rectification, and marketing preferences where applicable.',
      'Security',
      'Encryption, access control, and vendor oversight on processors.',
    ),
    bullets: ['Data protection officer and grievance redressal contacts on the full policy'],
  },
  terms: {
    title: 'Terms of use',
    lead: 'Rules for using our websites, apps, and digital services.',
    cards: cards(
      'Access',
      'Accurate information, no misuse, and compliance with security prompts.',
      'Content',
      'Trademarks, copyright, and permitted reuse of information.',
      'Liability',
      'Limits and indemnities as set out in the complete terms document.',
    ),
    bullets: ['Updates with notice; continued use may constitute acceptance of changes'],
  },
  disclaimer: {
    title: 'Disclaimer',
    lead: 'General information on this site; products are subject to approval and local availability.',
    cards: cards(
      'No offer',
      'Content is not an offer in jurisdictions where a registration is required.',
      'Accuracy',
      'We strive for accuracy; rates and features can change without prior notice.',
      'Decisions',
      'You should read scheme documents and seek advice where needed before transacting.',
    ),
    bullets: ['Third-party links are provided for convenience; their policies govern use there'],
  },
}

export function getSectionCopy(id) {
  return (
    sectionCopy[id] || {
      title: 'Services',
      lead: 'Explore our banking and financial solutions.',
      cards: cards(
        'Products',
        'Accounts, cards, loans, and investments in one place.',
        'Service',
        'Digital and branch support with secure authentication.',
        'Help',
        'FAQs, forms, and customer care for your requests.',
      ),
      bullets: ['Use the main menu to go to a specific category'],
    }
  )
}

export const footerLinkToSlug = (label) => {
  const map = {
    'Savings Account': 'accounts',
    'Current Account': 'accounts',
    'Salary Account': 'accounts',
    'Safe Deposit Locker': 'accounts',
    'Credit Cards': 'cards',
    'Debit Cards': 'cards',
    'Forex Cards': 'forex',
    'Commercial Cards': 'cards',
    'Personal Loan': 'loans',
    'Home Loan': 'loans',
    'Car Loan': 'loans',
    'Gold Loan': 'loans',
    'Customer Care': 'support',
    'Raise a Concern': 'support',
    'FAQs': 'support',
    'Grievance Redressal': 'support',
  }
  return map[label] || 'support'
}
